kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-applier
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
  name: kube-applier
  labels:
    app: kube-applier
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: kube-applier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-applier
  template:
    metadata:
      labels:
        app: kube-applier
    spec:
      serviceAccountName: kube-applier
      containers:
        - name: kube-applier
          image: quay.io/utilitywarehouse/kube-applier:master
          env:
            - name: DIFF_URL_FORMAT
              value: "https://github.com/org/repo/commit/%s"
            - name: LOG_LEVEL
              value: "warn"
            - name: GIT_SSH_KEY_PATH
              value: "/etc/git-secret/ssh"
            - name: GIT_KNOWN_HOSTS_PATH
              value: "/etc/git-secret/known_hosts"
            - name: REPO_REMOTE
              value: "git@github.com:org/repo.git"
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 4000m
              memory: 512Mi
          ports:
            - containerPort: 8080
      volumes:
        - name: git-secret
          secret:
            secretName: ssh
            defaultMode: 0400
